# tools/amrfinderplus_db/.shed.yml

owner: "estrain"

name: "data_manager_amrfinderplus"

description: "A data manager for the AMRFinderPlus database."

long_description: "This tool provides a data manager for fetching, building, and installing the AMRFinderPlus database for use with the AMRFinderPlus Galaxy tool. It ensures that the database is available for analysis workflows."

homepage_url: "https://github.com/CFSAN-Biostatistics/galaxytrakr-tools"

type: unrestricted
categories:
  - "Tools"